language: python
python:
 - "3.6"
cache: pip
sudo: false

env:
  - DJANGO_SETTINGS_MODULE=project.settings.travis

install: pip install -r requirements-dev.txt

script:
  - flake8
  - python manage.py makemigrations simple_authentication
  - python manage.py migrate
  - python manage.py test
